### ISSUE TITLE
Library should not export XCTestDynamicOverlay

### ISSUE THREAD

**Issue by lukeredpath** [pointfreeco/swift-dependencies#13]
### Description

The @exported import of XCTestDynamicOverlay causes the use of `XCTFail` in tests and test helpers where you import both XCTest and Dependencies (or something that implicitly imports Dependencies like ComposableArchitecture) to result in a compiler error due to am ambiguous use of `XCTFail`.

This is effectively a regression of https://github.com/pointfreeco/swift-composable-architecture/issues/747 and I ran into this upgrading from TCA 0.45 to 0.49.

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-dependencies/issues) or [discussion](https://github.com/pointfreeco/swift-dependencies/discussions).

### Expected behavior

You should be able to use XCTFail in tests/test helpers without error.

### Actual behavior

Fails to compile.

### Dependencies version information

0.1.2

### Xcode version information

Xcode 14.2

**Comment by stephencelis** [comment]
Hey @lukeredpath! Just to get a better understanding of the bug, can you share a repro? We have quite a few suites that import both `ComposableArchitecture` and `XCTest` and haven't hit this yet, and it'd be nice to have some regression testing in place for any potential fix.

**Comment by lukeredpath** [comment]
[BugRepro.zip](https://github.com/pointfreeco/swift-dependencies/files/10393456/BugRepro.zip)

Sure - the above project reproduces the error when compiling the test target.

**Comment by davdroman** [comment]
Relates to https://github.com/pointfreeco/xctest-dynamic-overlay/discussions/45

IMO it'd be a shame to stop exporting `XCTDynamicOverlay`, so that's why I suggested `@_disfavoredOverload`.

**Comment by stephencelis** [comment]
Fixed upstream, thanks!
