### ISSUE TITLE
@DependencyClient and inout parameters

### ISSUE THREAD

**Issue by Alex293** [pointfreeco/swift-dependencies#146]
### Description

The code generated by @DependencyClient is incorrect for inout parameters and generate invalid swift code. it should explicitly refuse to generate code or if possible generate valid code.

### Checklist

- [X] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-dependencies/issues) or [discussion](https://github.com/pointfreeco/swift-dependencies/discussions).

### Expected behavior

```
@DependencyClient
public struct AuthenticationClient {
    var authenticateRequest: (_ urlRequest: inout URLRequest) async throws  -> Void
}
```

Should generate valid swift code

### Actual behavior

The code generated : 
```
func authenticateRequest(urlRequest p0: inout URLRequest) async throws  -> Void {
    try await self.authenticateRequest(p0)
}

private var _authenticateRequest: (_ urlRequest: inout URLRequest) async throws  -> Void = { _ in
    XCTestDynamicOverlay.XCTFail("Unimplemented: 'authenticateRequest'")
    throw DependenciesMacros.Unimplemented("authenticateRequest")
}
```
is not valid code: Passing value of type 'URLRequest' to an inout parameter requires explicit '&'

### Dependencies version information

1.1.1

### Xcode version information

15.0.1

**Comment by mbrandonw** [comment]
Hey @Alex293, good catch! Do you have any interest in diving into this and trying to fix it? No worries if not, we will take a look soon.

**Comment by Alex293** [comment]
I'd love to. I'll have a look within a couple days and ping you if I'm struggling, Idon't have much experience with SwiftSyntax but I was looking to dive in.
