### ISSUE TITLE
`@DependencyClient` and `@autoclosure` parameters

### ISSUE THREAD

**Issue by xiii111** [pointfreeco/swift-dependencies#155]
### Description

This is similar to https://github.com/pointfreeco/swift-dependencies/issues/146. The code generated by `@DependencyClient` is incorrect for `@autoclosure` parameters and generate invalid swift code. it should explicitly refuse to generate code or if possible generate valid code.

### Checklist

- [X] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-dependencies/issues) or [discussion](https://github.com/pointfreeco/swift-dependencies/discussions).

### Expected behavior

```swift
@DependencyClient
public struct DemoClinet {
    public var execute: (_ closure: @autoclosure () -> String) -> Void
}
```

Should generate valid swift code

### Actual behavior

The code generated :

```swift
public func execute(closure p0: @autoclosure () -> String) -> Void {
    self.execute(p0)  // Error occurs: 'Add () to forward @autoclosure parameter'
}

private var _execute: (_ closure: @autoclosure () -> String) -> Void = { _ in
    XCTestDynamicOverlay.XCTFail("Unimplemented: 'execute'")
}
```

is not valid code: `Add () to forward @autoclosure parameter`

### Dependencies version information

1.1.2

### Xcode version information

15.0.0

**Comment by stephencelis** [comment]
@xiii111 Good catch! Do you have any interest in trying to tackle the problem with a pull request? No worries if not. We'll try to get to it soon otherwise :smile:

**Comment by xiii111** [comment]
@stephencelis Absolutely, I'll give it a try! However, I'm not familiar with SwiftSyntax, so if I can't finish it by the end of this week, I'll reach out to let you know.
