### ISSUE TITLE
iOS 18 - OpenURL doesn't work as expected

### ISSUE THREAD

**Issue by djpearce** [pointfreeco/swift-dependencies#220]
### Description

The provided openURL() is not functioning on iOS 18, as in the App never receives the deep link via the `AppDelegate` or `openURL`.

Same code that was functioning on iOS 17 is not working on iOS 18.

```swift 
  case let .tappedButton(url):
      return .run { _ in
          await openURL(url)
      }
```

### Checklist

- [X] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [x] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-dependencies/issues) or [discussion](https://github.com/pointfreeco/swift-dependencies/discussions).

### Expected behavior

I expect the URL to attempt to open.

### Actual behavior

the URL does not attempt to open.

### Steps to reproduce

1. With openURL
2. set breakpoint when receiving URL
3. no URL is hit

[OpenURLExample.zip](https://github.com/user-attachments/files/15780098/OpenURLExample.zip)

### Dependencies version information

1.3.0

### Destination operating system

iOS 18

### Xcode version information

Version 16.0 beta (16A5171c)

### Swift Compiler version information

```shell
swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: arm64-apple-macosx14.0
```

**Comment by mbrandonw** [comment]
Hi @djpearce, have you confirmed that `openURL` still works in a vanilla SwiftUI? Since iOS 18 is only in its first beta release it could be an issue with the beta.

**Comment by mbrandonw** [comment]
Hi @djpearce, sorry I didn't see the project attached. I do see the problem.

There may be a chance that what we are doing here is not legit:

https://github.com/pointfreeco/swift-dependencies/blob/76b98dea40d2b13ace67216cbb100cef673e8267/Sources/Dependencies/DependencyValues/OpenURL.swift#L23

It's just kind of a hack we tried out to get a consistent `openURL` API across all platforms. Or this could just an issue with betas that will start working again at some point. Hard to say really.

**Comment by djpearce** [comment]
@mbrandonw, yeah sounds good, just raising it so it's on y'all radar and for anyone else who may be seeing it. I'll keep an eye on it as well and report back as well.

**Comment by stephencelis** [comment]
We originally called to the non-`EnvironmentValues` APIs, but decided to leverage `EnvironmentValues` here in order to work around an issue with Tuist and app extensions: https://github.com/pointfreeco/swift-composable-architecture/pull/1714

While in hindsight we think the workaround is probably not a legit thing to do, we'd like to consider what the best path forward is.

@tgrapperon I know it's been awhile but you spent some time noodling over the problem. Do you remember any potential alternative fixes?

**Comment by stephencelis** [comment]
(Adding the "apple bug" label since this regression is due to a change in Apple's SDKs.)

**Comment by shijinliang** [comment]
[UIApplication](https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-18-release-notes#UIApplication)
[Resolved Issues](https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-18-release-notes#Resolved-Issues)
Fixed: Applications built with iOS 18.0, iPadOS 18.0, Mac Catalyst 18.0, or tvOS 18.0 SDKs will call to the deprecated method UIApplication.openURL(_:). The specified URL will not open and will always return false. (125695759)

**Comment by djpearce** [comment]
> [UIApplication](https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-18-release-notes#UIApplication)
> 
> [Resolved Issues](https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-18-release-notes#Resolved-Issues)
> 
> Fixed: Applications built with iOS 18.0, iPadOS 18.0, Mac Catalyst 18.0, or tvOS 18.0 SDKs will call to the deprecated method UIApplication.openURL(_:). The specified URL will not open and will always return false. (125695759)

Great find!

Waiting to see it working on the new beta version and will report back and close.

**Comment by mbrandonw** [comment]
I may be misunderstanding the tech note, but that seems to imply that the deprecated `UIApplication.openURL(_:)` is now expected to not work. They are turning it off completely, which isn't surprising because it has been deprecated for a very long time. Instead you are expected to call [this](https://developer.apple.com/documentation/uikit/uiapplication/1648685-open) API instead.

So I don't think that tech note really has any bearing on the issue here. I think what we are going to have to do is stop using `EnvironmentValues` entirely and just use a platform specific `openURL`, which might also mean losing `openURL` on some platforms.

**Comment by stephencelis** [comment]
@djpearce Thanks for offering to help move things forward!

I think reverting is the way to go, but we should try to avoid breaking things for Tuist users. @tgrapperon suggested using `@available(iOSApplicationExtension, unavailable)` as an alternative to the current `EnvironmentValues` solution. Want to explore that against the Tuist example and if everything looks good we can merge?

**Comment by djpearce** [comment]
> Want to explore that against the Tuist example and if everything looks good we can merge?

Yes, I'll give it a shot here and see what I come up with. I haven't used Tuist before, but have been meaning to run a project for it locally anyway

**Comment by djpearce** [comment]
@mbrandonw @stephencelis Good news! After spending the night exploring Tuist and various solutions, I realized I hadn't yet updated to iOS 18 Beta 5. Just downloaded the new Xcode and simulator runtimes and everything is working as expected with no changes.

Going to close this bug as Beta 5 solves this.

**Comment by mbrandonw** [comment]
Hi @djpearce, I'm not able to confirm this. You are saying that `@Dependency(\.openURL)` now works in beta 5? It doesn't seem to work for me.

**Comment by wattson12** [comment]
> Hi @djpearce, I'm not able to confirm this. You are saying that `@Dependency(\.openURL)` now works in beta 5? It doesn't seem to work for me.

In our app (built against iOS 17.x SDK) the open URL effect had stopped working but that seems to have been restored from my testing in dev betas 5 and 6

I also see this code working as expected on and iOS 18 and 17.5 sims built from Xcode 16.0 beta 5 (16A5221g)  

```
@Reducer
struct ContentFeature {
    typealias State = Void
    typealias Action = Void
    
    @Dependency(\.openURL) var openURL
    
    var body: some ReducerOf<Self> {
        Reduce { _, _ in .run { _ in await openURL(URL(string: "https://pointfree.co")!) } }
    }
}

struct ContentView: View {
    let store: StoreOf<ContentFeature> = .init(initialState: (), reducer: ContentFeature.init)
    
    var body: some View {
        Button("Open URL") { store.send(()) }
    }
}
```

**Comment by jaychen04** [comment]
In my demo app, it still doesn’t work on Xcode beta6 and iOS Beta.Is any one succeed?

**Comment by mbrandonw** [comment]
Actually this does seem to work for me now. @jaychen04, can you provide a repro project of the problem?

**Comment by jaychen04** [comment]
@mbrandonw Thank you！Could tell me which version of iOS and XCode you are using？

**Comment by mbrandonw** [comment]
@jaychen04, I am using Xcode 16 beta 5 and iOS 18.

**Comment by marshall86** [comment]
i'm experiencing an issue on ios 18.0.1 I have a link that first goes in Safari and then it should open the app. Since I have upgraded to the latest ios version, the the app doesn't open and Safari gives me a message: "the site is repeatedly trying to open another application". Do you know the reason? is it an ios 18.0.1 bug? never had this issue before

**Comment by DanKorkelia** [comment]
On related issue. Just been having similar issues and we had some luck using this option

let handle = userActivity.startCallHandle // The `UserActivity` structure the system provides; the `startCallHandle` property is the phone number the system is passing to your app.
    var urlComponents = URLComponents()
    urlComponents.scheme = **"telephony"**
    urlComponents.path = handle

iPad would not make calls using tel:// but changing schema to telephony made a difference. 
Xcode 16.2 iPad OS 18.3
