### ISSUE TITLE
Sending 'element' risks causing data races error when compiling v1.3.2 with Xcode Version 16.0 beta 3 (16A5202i) 

### ISSUE THREAD

**Issue by orj** [pointfreeco/swift-dependencies#243]
### Description

When compiling version 1.3.2 of swift-dependencies reports an error: `Sending 'element' risks causing data races` on line 56 of Deprecations.swift

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-dependencies/issues) or [discussion](https://github.com/pointfreeco/swift-dependencies/discussions).

### Expected behavior

The library should compile cleanly on Xcode 16.

### Actual behavior

The library does not compile.

### Steps to reproduce

Compile swift-dependencies as a dependency in a Swift project with Xcode Version 16.0 beta 3 (16A5202i).

### Dependencies version information

1.3.2

### Destination operating system

iOS 17.5

### Xcode version information

Xcode Version 16.0 beta 3 (16A5202i)

### Swift Compiler version information

```shell
swift-driver version: 1.111.2 Apple Swift version 6.0 (swiftlang-6.0.0.5.15 clang-1600.0.22.6)
Target: arm64-apple-macosx14.0
```

**Comment by hallee** [comment]
I have a PR that fixes this: https://github.com/pointfreeco/swift-dependencies/pull/241
