### ISSUE TITLE
Issue with macro and `any AsyncSequence`

### ISSUE THREAD

**Issue by brzzdev** [pointfreeco/swift-dependencies#312]
### Description

With `eraseToStream()` now being deprecated, I was switching my dependencies over to `any AsyncSequence<Element, Failure` and found that using `.never` no longer works (expected), and that switching to `AsyncStream.never` causes a compiler error.
It appears to be some interaction between the macro and unimplemented, as:
Without the macro
```
struct Example {
  var exampleSequence: () -> any AsyncSequence<Int, Never> = {
    unimplemented(
      "",
      placeholder: AsyncStream.never
    )
  }
}
```
and without unimplemented
```
@DependencyClient
struct Example {
  var exampleSequence: () -> any AsyncSequence<Int, Never> = {
    AsyncStream.never
  }
}
```
both work
but
```
@DependencyClient
struct Example {
  var exampleSequence: () -> any AsyncSequence<Int, Never> = {
    unimplemented(
      "",
      placeholder: AsyncStream.never
    )
  }
}
```
causes a compiler error.

Also worth noting that explicitly casting `AsyncStream.never as any AsyncSequence<Int, Never>` builds, but is obviously unergonomic to cast like that in every unimplemented method

### Checklist

- [X] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-dependencies/issues) or [discussion](https://github.com/pointfreeco/swift-dependencies/discussions).

### Expected behavior

Above example compiles

### Dependencies version information

1.5.2

### Destination operating system

macOS 15

### Xcode version information

16.1

### Swift Compiler version information

```shell
swift-driver version: 1.115 Apple Swift version 6.0.2 (swiftlang-6.0.2.1.2 clang-1600.0.26.4)
Target: arm64-apple-macosx15.0
```

**Comment by stephencelis** [comment]
@brzzdev Thanks for the report! I just looked into it, and it looks like it's a Swift bug.

You can repro using just the `@DependencyEndpoint` macro:

```swift
struct Example {
  @DependencyEndpoint
  var exampleSequence: () -> any AsyncSequence<Int, Never> = {
    unimplemented(
      "",
      placeholder: AsyncStream.never
    )
  }
}
```

> Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.

I'd recommend filing a bug with Swift if you can!

While we're open to local workarounds to fix the issue, we probably won't have time to investigate ourselves. In the meantime I'd probably recommend not using `unimplemented` here and instead reproduce what it does, which is probably shorter and more understandable:

```swift
struct Example {
  @DependencyEndpoint
  var exampleSequence: () -> any AsyncSequence<Int, Never> = {
    reportIssue()
    return AsyncStream.never
  }
}
```
