### ISSUE TITLE
Testing failure for overridden dependency

### ISSUE THREAD

**Issue by eimantas** [pointfreeco/swift-dependencies#57]
### Description

I have a framework target and its unit tests. I have a dependency of shape `(String,String) -> EffectTask<Result<A,B>>`. It has a live value in framework target and an extension of its key in tests target with a `testValue`.

I wrote a test that exercises a reducer's event and uses said dependency. The dependency also has `testValue` defined in the test case file. The problem is that the `testValue` should override the network call. However I get a few errors where most of them _I believe_ stem from `swift-dependencies` not being able to find overridden dependency. The failures are:

- dependency doesn't have a test value (culprit)
- an effect returned is still running (network request in live and simple `EffectTask(value:)` in test
- expected but did not receive an action (because the previous effect is still running, because it didn't find a testValue for the dependency);

I read the test gotcha, however I don't believe it's valid in my case as I am testing a framework target. I also read [this thread](https://github.com/pointfreeco/swift-dependencies/discussions/48) where Brandon writes

> You aren't allowed to extend a protocol with default implementations from another module.

Is this the case? I am not extending a protocol, rather protocol's adoption from module A (framewokr) in module B (tests).

### Checklist

- [X] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-dependencies/issues) or [discussion](https://github.com/pointfreeco/swift-dependencies/discussions).

### Expected behavior

I would expect the tests to run smoothly as they don't exercise complex business logic. Simple action that triggers request/response and then maps to resulting success/failure action.

### Actual behavior

The dependency is not found (ostensibly), the trigger effect is still running and result action is not received.

### Dependencies version information

0.1.4

### Destination operating system

iOS 16

### Xcode version information

14.2

### Swift Compiler version information

```shell
Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
Target: x86_64-apple-macosx13.0
```

**Comment by tgrapperon** [comment]
Hey @eimantas!
> The dependency also has testValue defined in the test case file.

This doesn't seems right. If the dependency conforms to `DependencyKey` in the framework, it is fully defined when the framework is built, and the value you provide in the test file will not participate in `Dependencies`'s logic.

If you want to assign values to your dependency when testing, you should use `withDependencies`, or, in TCA, the `prepareDependencies` closure of `TestStore`.

You should probably try to define an "`unimplemented`" `testValue` in the framework, and assign the `testValue` value you defined in the test file to the dependency using the `prepareDependencies` closure of `TestStore`.

**Comment by eimantas** [comment]
Thanks for the reply. I have added the default implementation which raises (`fatalError(...)`). The problem now is that my `prepareDependencies` closure of `TestStore` doesn't override them in any way :( it's like the closure doesn't even exist although the breakpoint in it, when running the tests, gets hit.

**Comment by tgrapperon** [comment]
The testing gotchas where updated a few days ago with one sneaky issue when you link your test target with the `Dependencies` module. This is fairly easy to check, as Xcode will print many "Duplicate implementation" message before running the tests.

Do you think you have an escaping closure somewhere? It should rarely happen when using TCA though, but this is typically something that escapes the `testValue` override.

I would try to put a breakpoint on the `fatalError` of `testValue` and check who's hitting that, and under which context.

**Comment by mbrandonw** [comment]
Hi @eimantas, can you provide a sample project that reproduces the problem?

**Comment by eimantas** [comment]
@tgrapperon — I am using Dependency package as TCA dependency, so not linking it directly or importing it all.

@mbrandonw — the vanilla SwiftUI works as expected. I want to believe that my complex project structure with huge codebase is at fault here although its rather modularized.

**Comment by mbrandonw** [comment]
Hi @eimantas, do you have any update for this? If not can we close it and you can  start a discussion if you have more you want to share?

**Comment by eimantas** [comment]
You can definitely close this. Sorry for the late response. It seems that this was mysterious issue with dependencies in my cobweb of a project, not the issue of the library.
