### ISSUE TITLE
this repo no longer builds on windows

### ISSUE THREAD

**Issue by stevenbrix** [pointfreeco/swift-dependencies#90]
### Description

before https://github.com/pointfreeco/swift-dependencies/pull/84 went in, this repo was able to build on Windows, now that there are API calls to `dlopen` and `dlsym` pulling the latest package no longer builds

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-dependencies/issues) or [discussion](https://github.com/pointfreeco/swift-dependencies/discussions).

### Destination operating system

Windows

**Comment by kabiroberai** [comment]
Thanks for flagging this; I see two viable approaches here, both involving some modifications to the `swift_task_enqueueGlobal_hook` getter:

1. Use [GetProcAddress](https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-getprocaddress) and co to achieve something similar using Win32 APIs. I'm admittedly less familiar with Windows though so there are unknown unknowns here for me (eg are dynamic linker APIs available under UWP? do people even use that anymore?)
2. Just `return nil` under Windows (or basically anything other than Linux/Darwin) for now — I don't know if the test suite passes on other platforms anyway, and it seems like this repo doesn't have a CI setup for other platforms atm. This will be sufficient to get the package building for clients so it feels like a good stopgap.

Will defer to Stephen and Brandon for the final call on this.

**Comment by stephencelis** [comment]
@stevenbrix Thanks for the report! We'd love to get some Windows CI on this repo (and others), but the GitHub Actions we relied on to do so have all ended up failing over time. Do you have any experience setting up GitHub Actions for Windows in a reliable way?

@kabiroberai We'd definitely be down for the first option once we have CI in place that can help validate it, but I think we could probably at least get things building again by compiling the helper out of `#if os(Windows)` for now. What do you think?

**Comment by kabiroberai** [comment]
@stephencelis I'm on board with that 👍

**Comment by stephencelis** [comment]
@kabiroberai It does, thanks for the poke! The helper is still not going to work on Windows, but maybe someone will contribute support soon.

**Comment by stevenbrix** [comment]
Sorry for the radio silence!

Thanks for getting this fixed. We've been doing a lot of work on stabilizing the swift toolchain on windows, when a trunk build with those fixes makes it in you might be able to update to it?

Is there anything you need from us to get things working?
